[tool.poetry]
name = "aoc2025"
version = "0.1.0"
package-mode = false

[tool.poetry.dependencies]
python = ">3.11"
scipy = ">1.0.0"
numpy = ">2.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
